# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestbuyproductwithaccount():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testbuyproductwithaccount(self):
    self.driver.get("http://127.0.0.1:8000/#/")
    self.driver.set_window_size(1053, 662)
    self.driver.find_element(By.CSS_SELECTOR, ".nav-link:nth-child(2)").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("haneen.tester@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("Hha12345")
    self.driver.find_element(By.CSS_SELECTOR, ".mt-3").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-xl-3:nth-child(1) strong").click()
    self.driver.execute_script("window.scrollTo(0,301)")
    self.driver.find_element(By.CSS_SELECTOR, ".w-100").click()
    self.driver.execute_script("window.scrollTo(0,198.6666717529297)")
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-3 > .form-control").click()
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".col-md-3 > .form-control")
    dropdown.find_element(By.XPATH, "//option[. = '1']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".w-100").click()
    self.driver.find_element(By.CSS_SELECTOR, ".justify-content-md-center").click()
    self.driver.find_element(By.ID, "city").click()
    self.driver.find_element(By.ID, "postalCode").click()
    self.driver.find_element(By.ID, "postalCode").click()
    self.driver.find_element(By.ID, "postalCode").click()
    element = self.driver.find_element(By.ID, "postalCode")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "postalCode").send_keys("16000")
    self.driver.find_element(By.ID, "country").click()
    self.driver.find_element(By.ID, "country").click()
    element = self.driver.find_element(By.ID, "country")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "country").click()
    self.driver.find_element(By.CSS_SELECTOR, ".my-3").click()
    self.driver.find_element(By.CSS_SELECTOR, ".my-3").click()
    self.driver.find_element(By.CSS_SELECTOR, ".w-100").click()
  
