# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_test(self):
    self.driver.get("http://127.0.0.1:8000/#/")
    self.driver.set_window_size(1053, 662)
    self.driver.find_element(By.CSS_SELECTOR, ".col-xl-3:nth-child(1) strong").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-xl-3:nth-child(1) strong").click()
    self.driver.find_element(By.CSS_SELECTOR, ".w-100").click()
    self.driver.execute_script("window.scrollTo(0,198.6666717529297)")
    self.driver.find_element(By.CSS_SELECTOR, ".w-100").click()
    self.driver.find_element(By.CSS_SELECTOR, ".my-3").click()
    self.driver.find_element(By.CSS_SELECTOR, ".my-3").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".my-3")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".w-100").click()
    self.driver.switch_to.frame(0)
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".paypal-button-number-0 > .paypal-button-label-container").click()
    self.vars["win9339"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win9339"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
  
